### ISSUE TITLE
Pyvenv vs. post_activate hook

### ISSUE THREAD

**Issue by axonal** [jorgenschaefer/pyvenv#23]
Hello,

It seems like the function for virtualenvwrapper_cd is not being found inside my emacs. When pyvenv-run-virtualenvwrapper-hook is run I get this error:

```
Output from the virtualenvwrapper hook post_activate:

/var/folders/3t/kgfvxm6x49df9t0y0k4gx2140000gn/T/pyvenv-virtualenvwrapper-41735Zaa: line 6: virtualenvwrapper_cd: command not found
```

Otherwise things seem to be working. I am assuming this is working and an OS X environment thing. Any  hints? It seems to be able to find virtualenvwrapper_cd from a shell within emacs.

**Comment by jorgenschaefer** [comment]
Thank you for the report, and sorry for the long delay – I was on vacation.

What is `virtualenvwrapper_cd`, and where is it defined? That file name suggests that it is called in some post-activate hook somewhere. Does your virtualenv define some post-activate hook?

**Comment by axonal** [comment]
I don't believe I run anything but the default post-activate hook...


virtualenvwrapper_cd is defined by virtualenvwrapper itself:

https://bitbucket.org/dhellmann/virtualenvwrapper/src/9c702672f47cb72f84a1471c3e46ad80286230ed/virtualenvwrapper.sh?at=master#cl-106

**Comment by jorgenschaefer** [comment]
Oh, indeed. That must be a "recent" addition – the virtualenvwrapper.sh I have here does not define this. This is weird. virtualenvwrapper should find itself, you'd think.

Is it possible that you have multiple virtualenvwrapper installations on your system, and your Emacs finds a different one from your normal shell?

**Comment by jorgenschaefer** [comment]
Lacking any updates on this, and having had no problems whatsoever like this, I assume this problem is resolved. I will close this issue – please do not hesitate to re-open if there are any further problems.

**Comment by sydneyweidman** [comment]
For anyone else who may read this post, I had the problem described above and the solution to #31 fixed the problem for me.

**Comment by wizmer** [comment]
I recently experienced this problem. I understand the problem but I have no solution.
The thing is that `virtualenvwrapper_cd` is not a shell command but a bash function defined in:
virtualenvwrapper.sh.

I can find it in my shell by typing the following command: `typeset -F | grep virtualenvwrapper_cd`
However if I type it in emacs using M-!, it does not find it. So the problem comes down to making Emacs aware of the functions defined in virtualenvwrapper.sh.

Temporary fix: You can disable the hook called in the `pyenv-activate` function. Just comment the line:
`(pyvenv-run-virtualenvwrapper-hook "post_activate")`
