### ISSUE TITLE
unable to start rpc process with ssh/vagrant?

### ISSUE THREAD

**Issue by ChillarAnand** [jorgenschaefer/pyvenv#26]
if i switch to a `venv` in local system, elpy-config shows

    Virtualenv........: d18 (/home/k3/.virtualenvs/d18)
    RPC Python........: 2.7.6 (/home/k3/.virtualenvs/d18/bin/python)

if i switch to a `venv` in ssh/vagrant, elpy config shows 

    Virtualenv........: pearl (/ssh:xxxx@xxx.xxx.xxx.xxx:/home/xxx/.virtualenvs/pearl)
    RPC Python........: 2.7.6 (/usr/bin/python)

**Comment by jorgenschaefer** [comment]
What version of virtualenvwrapper are you using in the respective environments?

This might be related to #25

**Comment by ChillarAnand** [comment]
i was using latest version. my bad. nvm

**Comment by ChillarAnand** [comment]
looks like this problem is not solved yet?

if i activate `venv` using `pyvenv-activate` which is in server elpy config shows 

```
Virtualenv........: pearl (/ssh:lrb@xxx.xxx.xxx.xxx:/home/lrb/.virtualenvs/pearl)
RPC Python........: 2.7.6 (/home/k3/.virtualenvs/pearl/bin/python)
Interactive Python: ipython (/home/k3/.virtualenvs/pearl/bin/ipython)
Syntax checker....: flake8 (/home/k3/.virtualenvs/pearl/bin/flake8)
```

here venv is activated but others have not cofigured properly?

**Comment by jorgenschaefer** [comment]
Oh, I did not see this correctly the first time, sorry about that – you are using some kind of virtualenv in tramp?

I'm afraid that won't work. Tramp does a lot of magic with Emacs internals to do what it does, but it breaks in interesting ways if you try to tweak it too far. Elpy does that, because it runs so many different processes and needs to communicate with them in various ways.

So, sorry, elpy does not work with tramp. I can highly recommend not using tramp but use sshfs instead for remote file editing. Or, even better, edit locally and use fab/git to deploy to your VM.

**Comment by ChillarAnand** [comment]
makes sense. thank you very much
