### ISSUE TITLE
Setting python-shell-interpreter?

### ISSUE THREAD

**Issue by cpitclaudel** [jorgenschaefer/pyvenv#48]
Hi there,

Is there a way to make C-c C-c and C-c C-p start an instance of the virtualenv-local python interpreter, instead of the global one? This magically works as long as pytjon-shell-interpreter is set to Python, but it doesn't if python-shell-interpreter is set to, e.g., `python3`.

I guess this would mean setting python-shell-interpreter variable locally when a virtualenv is activated?

Sorry if I'm misunderstanding something simple here.

**Comment by jorgenschaefer** [comment]
Hello! You could add functions to `pyvenv-post-activate-hook` and `pyvenv-post-deactivate-hook` to change `python-shell-interpreter` to `"python"` and `"python3"` respectively, maybe.

Or just always use virtualenvs, and always use `"python"` there …

**Comment by cpitclaudel** [comment]
Thanks! Do you see downsides to always doing this? Would you accept a PR implementing this? You obviously know a lot more about virtualenvs than I do :)

**Comment by jorgenschaefer** [comment]
> Do you see downsides to always doing this?

Assuming with "this" you mean adding those functions: Yes, people who configure this could be very confused as to why their explicit configuration is overridden.

If with "this" you meant always using virtualenvs: No, no downside as far as I know.

**Comment by cpitclaudel** [comment]
I didn't mean using these functions directly; rather, I meant extending pyvenv to set python-shell-interpreter upon activation by default.

**Comment by jorgenschaefer** [comment]
Same response for that.

**Comment by cpitclaudel** [comment]
But this wouldn't override anyone's default configuration, would it?

**Comment by cpitclaudel** [comment]
Oh, did you mean configuration of `python-shell-interpreter`?

**Comment by jorgenschaefer** [comment]
Yes

**Comment by cpitclaudel** [comment]
Ok :)

**Comment by benf-wspdigital** [comment]
@jorgenschaefer, I'm confused by this exchange; I got lost in a tangle of pronouns and articles, without knowing what they're referring to.

As I understand it, this request is to have ‘pyvenv’ set `python-shell-interpreter` when activating the virtualenv, because that  variable is what various other packages expect for the current active Python interpreter.

Is that right, @cpitclaudel? Does that match your understanding, @jorgenschaefer?

If so, I don't understand what the objection is. Isn't activation of a particular virtualenv exactly the type of action which *should* override the default Python shell interpreter, for the context of that virtualenv?

**Comment by cpitclaudel** [comment]
@benf-wspdigital That's correct; thanks for stating this better than I did :) 

Here's another problem that I ran into with the pyvenv: When a Lisp program starts a `python-shell-interpreter`, then the results in a virtualenv depend in a non-obvious way on the value of `python-shell-interpreter`.  Indeed, as long as `python-shell-interpreter` is left to the default value `"python"`, pyvenv's changes to the `exec-path` cause the virtualenv's `python` (possibly Python 3) to run.  However, if I customize `python-shell-interpreter` to `"python2"`, then running the same Lisp program now starts the system-wide python.

**Comment by jorgenschaefer** [comment]
> If so, I don't understand what the objection is.

@cpitclaudel changed the default behavior by telling Emacs "please start the command `python3`, not `python`". But then they expect Emacs to second-guess them and know that when a virtualenv is present, this explicit and deliberate customization is not meant to happen.

My position is that if you change the default behavior, it's also your responsibility to undo those changes in those cases where you do not like them.

**Comment by benf-wspdigital** [comment]
On 2016-10-09 03:09, Jorgen Schäfer wrote:
> @cpitclaudel <https://github.com/cpitclaudel> changed the default 
> behavior by telling Emacs "please start the command |python3|, not 
> |python|".

You mean in the `python-shell-interpreter` variable? Yes, that seems to 
be the right context-sensitive place to signal which Python interpreter 
to use.

> But then they expect Emacs to second-guess them and know that when a 
> virtualenv is present, this explicit and deliberate customization is 
> not meant to happen.

I don't understand what is at work in that statement.

Are you saying that the `python-shell-interpreter` variable is not meant 
to be customised?

Are you saying that the Emacs virtualenv integration should explicitly 
and deliberately ignore that variable?

Are you saying that Emacs should not detect a virtualenv?

My understanding is not that any second-guessing is needed. Rather, the 
Emacs virtualenv integration should use `python-shell-interpreter` to 
inform other code which Python interpreter is active for the virtualenv.

> My position is that if you change the default behavior, it's also your 
> responsibility to undo those changes in those cases where you do not 
> like them.
>

Yes.

Activating a Python virtualenv entails selecting the Python interpreter 
for that virtualenv.

Other code, which should not have to care about virtualenv status, looks 
to the current setting of `python-shell-interpreter` to query which 
Python interpreter to use.

So, entering and exiting a Python virtualenv should express the change 
of Python interpreter by setting the `python-shell-interpreter` variable 
on activation and deactivation, since that is where other code looks to 
see which Python shell interpreter is requested.

-- 

Ben Finney
ben.finney@wspdigital.com

**Comment by jorgenschaefer** [comment]
> Rather, the Emacs virtualenv integration should use `python-shell-interpreter` to inform other code which Python interpreter is active for the virtualenv.

Are you saying that the virtualenv integration should override an explicit configuration set by the user?

> Activating a Python virtualenv entails selecting the Python interpreter for that virtualenv.

I see where you are coming from. I do not agree, though.

When you start your python script with `#!/usr/bin/env python3`, it will not work even if you activate a virtualenv. I don't think Emacs should behave differently.

It is not Emacs' job to second-guess the user. If you want that to happen, you can easily set a post-activate hook to do that for you.

**Comment by cpitclaudel** [comment]
Hey @jorgenschaefer,

I let this thread bitrot a bit, but I'd like to fix it; the situation on the Flycheck side isn't optimal at the moment. I'd like your help with fixing this, if you could advise.

> Are you saying that the virtualenv integration should override an explicit configuration set by the user?

I didn't say it, but I very much agree.  I've run into this problem a bunch of times in my various packages; at the moment there's no decent source of truth for "which Python should I call", AFAICT.  Am I missing something?

In other words, if I write a package that calls Python, which interpreter should I use if I want to play nicely along elpy?

> It is not Emacs' job to second-guess the user. If you want that to happen, you can easily set a post-activate hook to do that for you.

I don't see much second-guessing going on here: I may be misunderstanding, but when I say "use this virtualenv in this buffer", I expect this to mean "tweak my python-mode variables to make it so that the virtualenv's Python is used".

To the point: on Flycheck's side, I'd like people to be able to say "use the current venv, or default to using python3".   I'm assuming people can't (yet, hopefully) change their system default python command to point to Python 3.  Is there a good way to achieve this, without complex extra configuration for the user?

Thanks a lot :)
