### ISSUE TITLE
Supporting Anaconda under Windows

### ISSUE THREAD

**Issue by Shellay** [jorgenschaefer/pyvenv#56]
It would be useful for this tool to support Anaconda environments under Windows as well.

Anaconda environment however has a different structure, which looks like
```

$WORKON_HOME
|-- my-venv
|    |-- Scripts
|    |    |-- activate.bat
|    |    |-- deactivate.bat
|    |    |-- pip.exe 
|    |    +-- ...
|    |-- python.exe
|    |-- python.pdb
|    +-- ...
|
+-- my-another-venv
```
which is neither covered by Unix nor Windows at
https://github.com/jorgenschaefer/pyvenv/blob/master/pyvenv.el#L161
since here no `bin` exists, and `python.exe` is not under `Scripts`

Adding one more `when` option like:
``` elisp
  (let ((new-directories (append
                          ;; Unix
                          (when (file-exists-p (format "%s/bin" directory))
                            (list (format "%s/bin" directory)))
                          ;; Windows
                          (when (file-exists-p (format "%s/Scripts" directory))
                            (list (format "%s/Scripts" directory)))
                          ;; Anaconda Windows
                          (when (file-exists-p (format "%s/python.exe" directory))
                            (list directory)))))
```
would solve this.

**Comment by jorgenschaefer** [comment]
Sounds like a great idea! Thank you for the detailed report and description :-) Do you want to create a PR for this change?

**Comment by hendrikweisser** [comment]
I would like to add a request to have the suggested change integrated into "pyvenv".

I tried to use "pyvenv" to support Anaconda environments for Python in Emacs, based on e.g. https://emacs.stackexchange.com/questions/20092/using-conda-environments-in-emacs. And it seemed to work (the correct environment appeared in the mode line), but the wrong Python version was executed when I started the interpreter. Trying to find a work-around or fix for this was frustrating, partially because there is "anaconda-mode" for Python in Emacs, which appeared in a lot of Google results.
