### ISSUE TITLE
pyvenv-mode sets virtualenv global?

### ISSUE THREAD

**Issue by swsnr** [jorgenschaefer/pyvenv#6]
I just looked at the code, and noticed that pyvenv mode sets a virtualenv globally, by directly assigning to `exec-path` and `process-environment`, without making these variables local.

As such, there can only be a single virtualenv per Emacs session, which seems like a questionable limitation to me.

What's the rationale for this?

**Comment by alyssa-kwan-cloverhealth** [comment]
Thank you for having done this. My automatic Elpy setup works because of it. I was wondering if there was any way to cache project level Python processes (specifically for Jedi). Right now, if I switch between buffers that are in different Elpy projects, each switch triggers a Jedi restart. I'm wondering if it would be possible to start the process buffer with a project-specific suffix, with a variable that resolves to the name of the current process buffer. Then RPC calls could resolve it and pick it up. I don't know enough about Emacs to know if that's safe. Thoughts? More than happy to submit a patch.

**Comment by alyssackwan** [comment]
(Previously posted from my work account. Deleted and copied.)

Thank you for having done this. My automatic Elpy setup works because of it. I was wondering if there was any way to cache project level Python processes (specifically for Jedi). Right now, if I switch between buffers that are in different Elpy projects, each switch triggers a Jedi restart. I'm wondering if it would be possible to start the process buffer with a project-specific suffix, with a variable that resolves to the name of the current process buffer. Then RPC calls could resolve it and pick it up. I don't know enough about Emacs to know if that's safe. Thoughts? More than happy to submit a patch.

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the suggestion. This is certainly possible, but quite a bit of work – sadly, virtualenvs are somewhat of a global state, so switching them is necessarily quite global, too. You could, instead, set `elpy-rpc-python-command` to the full path to the Python interpreter in the respective virtualenv for each buffer. As Elpy uses this path to find the right RPC process already, this should get you roughly the behavior you want. Not a nice solution, though.

Please do feel free to open a new issue for this feature request.
